# Generated by Django 4.2.7 on 2023-11-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_shopproduct_remove_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
