# Generated by Django 4.2.7 on 2023-11-19 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_shopproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='shopkeeper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.shopkeeper'),
        ),
    ]
