# Generated by Django 4.2.7 on 2023-11-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_shopproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
    ]
