# Generated by Django 4.2.7 on 2023-11-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('job_description', models.CharField(max_length=255)),
                ('candidate_name', models.CharField(max_length=255)),
                ('qualification', models.TextField()),
                ('contact', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.PositiveIntegerField()),
                ('resume', models.ImageField(blank=True, null=True, upload_to='pp_image')),
            ],
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='product_name',
        ),
    ]
