# Generated by Django 4.2.7 on 2023-11-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_career_rename_product_cart_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='career',
            name='email',
        ),
        migrations.RemoveField(
            model_name='career',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='career',
            name='candidate_name',
        ),
        migrations.AddField(
            model_name='career',
            name='candidate_name',
            field=models.ManyToManyField(related_name='Users', to='myapp.user'),
        ),
    ]
